// Generated by Wrangler on Sun May 28 2023 18:00:30 GMT+0900 (日本標準時)
interface Env {
  VERSION: "1.0.2";
  SERVER_URL: "https://manga.buntin.xyz";
  DISCORD_APPLICATION_ID: string;
  DISCORD_CHANNEL_ID: string;
  DISCORD_PUBLIC_KEY: string;
  DISCORD_TOKEN: string;
}
