// Generated by Wrangler on Wed May 17 2023 22:36:03 GMT+0900 (日本標準時)
interface Env {
	VERSION: "1.0.1";
  DISCORD_APPLICATION_ID: string;
  DISCORD_CHANNEL_ID: string;
  DISCORD_PUBLIC_KEY: string;
  DISCORD_TOKEN: string;
}
