// Generated by Wrangler on Sun May 28 2023 16:27:10 GMT+0900 (日本標準時)
interface Env {
	VERSION: "1.0.1";
	SERVER_URL: "http://localhost:11150";
  DISCORD_APPLICATION_ID: string;
  DISCORD_CHANNEL_ID: string;
  DISCORD_PUBLIC_KEY: string;
  DISCORD_TOKEN: string;
}
