name = "badcompany"
main = "src/index.ts"
compatibility_date = "2023-05-13"
usage_model = "bundled"
node_compat = true

[vars]
VERSION = "1.0.1"
SERVER_URL = "https://test.synthia-liz.com"
#SERVER_URL = "https://manga.buntin.xyz"
